name: Test Build

on: [pull_request]

jobs:
  build_backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.6]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn test
      run: |
        yarn test
